extraction:
  cpp:
    after_prepare: 
      - python report.py 80
  cobol:
    after_prepare: 
      - python report.py 80
  csharp:
    after_prepare: 
      - python report.py 80
  java:
    after_prepare: 
      - python report.py 80
  javascript:
    after_prepare: 
      - python report.py 80
  python:
    after_prepare: 
      - python report.py 80
